### ISSUE TITLE
Running the services from outside the cluster

### ISSUE THREAD

**Issue by piyushshri** [kow3ns/kubernetes-kafka#7]
Hi,
We are able to run the Kafka console producer and consumer from within the cluster, please add documentation/suggestion on how to run the service from outside the cluster (maybe through NodePort) without `nodectl run`

**Comment by tehlers320** [comment]
Assuming you have k8s set for each container to get its own IP simply change the advertisement address with an override and set your pod to provide the IP to you.

```
+          --override advertised.host.name=${MY_POD_IP} \

         env:
+        - name: MY_POD_IP
+          valueFrom:
+            fieldRef:
+              fieldPath: status.podIP
```
