### ISSUE TITLE
Leader Not available

### ISSUE THREAD

**Issue by Abby3017** [kow3ns/kubernetes-kafka#8]
I am creating kafka and zookeeper cluster through given manifest file. Clusters and created and running good. But when I created NodePort to access kafka through external IP, it is throwing me error saying 
```
WARN [Consumer clientId=consumer-1, groupId=console-consumer-25337] Error while fetching 
metadata with correlation id 11 : {test=LEADER_NOT_AVAILABLE}
 (org.apache.kafka.clients.NetworkClient)
```
I have tried Exposing kafka service externally issue suggestion, but still I am getting the error.
Any suggestion will help. Thank You

**Comment by bradfordwagner** [comment]
Hey @Abby3017 not sure if you were able to work through this. I am currently trying to work around this as well. I'm able to telnet to the container when using a nodeport per replica. I also found [these charts](https://sourcegraph.com/github.com/helm/charts@master/-/tree/incubator/kafka) they may be a helpful resource. 

Were you able to work through this?

**Comment by Abby3017** [comment]
Hey, thing is in file first you have specify the **advertised host name** in kafka command list, 
also in listeners here it is mentioned PLAINTEXT://:9093 and I changed it to **PLAINTEXT://0.0.0.0:9093** as my whole service are hosted in same node so that it can listen to port 9093 in the given machine local ip. 
Its just some configuration issue if It still doesn't work, try it on minikube and try to hit it from your local machine, then you can get more idea about your problem.
